version: 2
jobs:
  build:
    working_directory: /go/src/github.com/illfate/social-tournaments-service
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: make dep
      - run:
          name: Build
          command: make
  test:
    working_directory: /go/src/github.com/illfate/social-tournaments-service
    docker: 
      -image: mysql:5.7.26
    steps:
      - run:
          name: Import data
          command: |
            mysql -u root -p$PASS -h 127.0.0.1<sql/user.sql
            mysql -u root -p$PASS -h 127.0.0.1<sql/tournament.sql   
      - run:
          name: test
          command: make test
                