version: 2
jobs:
  build:
    working_directory: ~/social-tournaments-service
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: make dep
      - run:
          name: Build
          command: make

  test:
    working_directory: ~/social-tournaments-service
    docker: 
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test

  docker-publish:
    working_directory: ~/social-tournaments-service
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Log in docker hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PWD
      - run:
           name: Build image
           command: docker build -t illfate/sts .
      - run:
          name: Push image to Docker Hub
          command: docker push illfate/sts

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test :
          requires:
            - build
      - docker-publish:
          requires:
            - test
          filters:
            branches:
              only: master
