version: 2
jobs:
  build:
    working_directory: /go/src/github.com/illfate/social-tournaments-service
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: make dep
      - run:
          name: Build
          command: make
