version: 2
jobs:
  build:
    working_directory: /go/src/github.com/illfate/social-tournaments-service
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: make dep
      - run:
          name: Build
          command: make
  test:
    working_directory: /go/src/github.com/illfate/social-tournaments-service
    docker: 
      - image: circleci/golang:latest
      - image: circleci/mysql:5.7.26
    steps:
      - run:
          name: Install mysql client; import data
          command: |
           sudo apt-get install mysql-client
           cat $Circle_Working_Directory/sql/user.sql $Circle_Working_Directory/sql/tournament.sql | mysql -uroot -p2010  
      - run:
          name: Tests
          command: make test
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test :
          requires:
            - build
      